# postgresql

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: ruby-clan-dev

test:
  <<: *default
  database: ruby-clan-test

production:
  <<: *default
  database: postgres
  username: postgres
  password: ruby-clan
